name: lalia
description: A password manage application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 工具类
  common_utils: ^1.1.3
  #bmob 云开发
  data_plugin: ^0.0.17
  # 图片处理插件
  extended_image: 0.7.2
  # 文字处理插件
  extended_text:  ^0.7.1
  # 弹出底部通知
  fluttertoast: ^3.1.3
  # swiper
  flutter_swiper: ^1.1.6
  # 拟态UI
  neuomorphic_container: ^2.0.3
  # 数据库
  sqflite: ^1.2.0
  # 应用路径
  path_provider: ^1.5.1
  # 密码加密
  encrypt: ^4.0.0
  # 文件管理
  flutter_file_picker: ^0.0.3
  # 路径选择
  directory_picker: ^1.0.0
  # 打开链接
  url_launcher: ^5.2.7
  # 状态管理
  provider: ^3.2.0
  # 路由管理
  fluro: ^1.6.3
  # 持久化
  shared_preferences: ^0.5.6
  # 依赖注入
  get_it: ^3.0.3
  # 生物识别
  local_auth: ^0.6.1
  like_button: ^0.2.0
  #  autofill_service:
  #       git:
  #         url: https://github.com/authpass/autofill_service

  markdown_widget:
    path: plugins/markdown_widget
  # 屏幕尺寸管理
  flutter_screenutil: ^0.7.0
  flutter_native_image: ^0.0.5
  fab_circular_menu: ^1.0.0
  multi_image_picker: 4.6.0
  image_picker: ^0.6.6+1
  # 汉字转拼音
  lpinyin: ^1.0.9
  # 网络请求
  dio: ^3.0.8
  flare_flutter: ^2.0.3
  # 设备信息
  device_info: ^0.4.1+4
  # 分享功能
  share: ^0.6.3+6
  xml: ^3.5.0
  palette_generator: ^0.2.2
  font_awesome_flutter: ^8.8.1
  autofill_service:
    path: plugins/autofill_service
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/avatars/
    - assets/flrs/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
